export const FETCHING_STAFF_REQUEST = 'FETCHING_STAFF_REQUEST';
export const FETCHING_STAFF_SUCCESS = 'FETCHING_STAFF_SUCCESS';
export const FETCHING_STAFF_FAILURE = 'FETCHING_STAFF_FAILURE';

// Staff Action
export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAILURE = 'DELETE_STAFF_FAILURE';
export const SWIPE_TO_CHOOSE_DELETEID = 'SWIPE_TO_CHOOSE_DELETEID';

// Table Action 
export const FETCHING_TABLE_REQUEST = 'FETCHING_TABLE_REQUEST';
export const FETCHING_TABLE_SUCCESS = 'FETCHING_TABLE_SUCCESS';
export const FETCHING_TABLE_FAILURE = 'FETCHING_TABLE_FAILURE';
export const CHOOSE_A_TABLE = 'CHOOSE_A_TABLE';

// Item Action
export const FETCHING_ITEM_REQUEST = 'FETCHING_ITEM_REQUEST';
export const FETCHING_ITEM_FAILURE = 'FETCHING_ITEM_FAILURE';

export const FETCHING_FOOD_SUCCESS = 'FETCHING_ITEM_SUCCESS';

export const FETCHING_DRINK_SUCCESS = 'FETCHING_DRINK_SUCCESS';

export const FETCHING_DESSERT_SUCCESS = 'FETCHING_DESSERT_SUCCESS';

export const FETCHING_FRIED_SUCCESS = 'FECTCHING_FRIED_SUCCESS';

export const FETCHING_HOTPOT_SUCCESS = 'FETCHING_HOTPOT_SUCCESS';

export const FETCHING_NOODLE_SUCCESS = 'FETCHING_NOODLE_SUCCESS'; 
