export const FETCHING_STAFF_REQUEST = 'FETCHING_STAFF_REQUEST';
export const FETCHING_STAFF_SUCCESS = 'FETCHING_STAFF_SUCCESS';
export const FETCHING_STAFF_FAILURE = 'FETCHING_STAFF_FAILURE';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAILURE = 'DELETE_STAFF_FAILURE';
export const SWIPE_TO_CHOOSE_DELETEID = 'SWIPE_TO_CHOOSE_DELETEID';

export const FETCHING_TABLE_REQUEST = 'FETCHING_TABLE_REQUEST';
export const FETCHING_TABLE_SUCCESS = 'FETCHING_TABLE_REQUEST';
export const FETCHING_TABLE_FAILURE = 'FETCHING_TABLE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CHOOSE_A_TABLE = 'CHOOSE_A_TABLE';